### PR TITLE
commands

### PR DESCRIPTION
**Pull request by deantheking**

### CODE REVIEW

**Comment by yihau** [comment]
hi there!

**Comment by yihau** [comment]
hi there!

**Comment by yihau** [comment]
hi there!

**Comment by yihau** [comment]
hello!

**Comment by yihau** [comment]
hello!

**Comment by deantheking** [comment]
hello

**Comment by yihau** [comment]
hello

**Comment by yihau** [comment]
hello!

**Comment by deantheking** [comment]
hello!

**Comment by deantheking** [comment]
!help

**Comment by yihau** [comment]
!help

**Comment by deantheking** [comment]
hello

**Comment by deantheking** [comment]
!help

**Comment by yihau** [comment]
hello!

**Comment by yihau** [comment]
!help

**Pull request closed without merging**
